import './globals.css'
import { Inter } from 'next/font/google'

import Header from '@/components/Header'
import ThemeRegistry from './ThemeRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Crypto portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: 'mui' }}><Header />{children}</ThemeRegistry>
      </body>
    </html>
  )
}
